[package]
name = "testing_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_common_assets = { version = "0.10.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.117"
